### PR TITLE
Detach instance when spot termination notification is received

### PR DESCRIPTION
**Pull request by adeshrd**
When a spot instance termination event is triggered, the lambda will get the
region and the instance id from the event data. With this data, it will detach
that instance.

# Issue Type

- Feature Pull Request

## Summary

The template now contains another CloudWatch EventRule to trigger the lambda 
when a spot instance termination notification is received.

The lambda detaches the instance when it receives the termination notification from
CloudWatch.

Note: The new EventRule is only present in the cloudformation template. 

## Code contribution checklist

1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/cristim/autospotting/blob/master/terraform/autospotting.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by adeshrd** [comment]
Thanks please do. Since this is my first time on Go I might have missed some things. Till then I will work on getting that coverage done.

**Comment by cristim** [comment]
The code looks good to me, I'm just not sure how to handle the Cloudwatch event situation I mentioned on gitter.

The spot termination event needs to be created in all regions and linked to the Autospotting Lambda function deployed in a single region. We have to find a way to deploy it, maybe using a custom Cloudformation resource. I am also not sure how to handle this on terraform

**Comment by adeshrd** [comment]
This was more troublesome than I thought but I was able to create those EventRules across regions. Have mentioned in more detail in commit comments

**Comment by cristim** [comment]
I decided to merge this as it is, if anyone wants the old behavior badly enough to submit a PR to make it configurable, I'd happily consider it.

**Pull request merged**
