### PR TITLE
Sqs workflow improvements

### PR DESCRIPTION
**Pull request by mello7tre**
guidelines:
* all replacement of ondemand with spot should be handled by sqs
messages and for the same ASG be sequentially
* spot life "outside asg" should be as short as possible
* should be possible to run without using SQSQueue, but ONLY wihout using
event based replacement too (cron only, so that cannot run at the same time two AS execution)
* only one method, swapWithGroupMember, is used to do ondeamnd
replacement

AS = Autospotting
CW = CloudWatch
SQS = Sqs Queue
CRON = Cron Schedule

1) CW ondemand event:
send message to SQS

2) SQS ondemand event:
launch spot replcament - wait for spot running - replace with
swapWithGroupMember

3) CW spot event:
do nothing (it's' needed to avoid intercepting spot launch of point 1)

4) CRON need to launch spot to replace ondemand:
if SQS is enabled we send message to SQS simulating an ondemand
  (ondemand launch)
  message
if SQS is disabled we directly launch spot replacement

5) CRON found spot to attach
if SQS is enabled we send message to SQS (spot launch)
if SQS is disabled we directly call swapWithGroupMember (by
  replaceOnDemandInstanceWithSpot)

6) SQS spot event:
replace with swapWithGroupMember

For point 4 sqs enabled, sending the message to the queue assure a
faster replacement, we do not need to wait for the next cron execution.

To be sure that all replacement for the same ASG (that can change ASG
max size and pause and resume services), are handled in a sequential
way, we use for SQS grouId ONLY the string {Region}-{AsgName}.

# Issue Type

- Feature Pull Request
- Bugfix Pull Request
- Documentation Pull Request

## Code contribution checklist

1. [ ] I hereby allow the Copyright holder the rights to distribute this piece of
   code under any software license.
1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [ ] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by cristim** [comment]
Why not handle everything in step 5 without SQS?

We could then entirely delete step 6 and have step 5 do the replacement like we anyway do if SQS is disabled.

**Comment by mello7tre** [comment]
because, when cron event start there could be another AS lambda running (triggered by sqs), both acting on the same ASG.

**Review by cristim — APPROVED** [review]
Looks pretty good, thanks!

**Comment by cristim** [comment]
oh, I just realized the tests are broken, I'll look into them within the next few days.

**Comment by mello7tre** [comment]
Yes, they was already broken in initial PR. Even gofmt was giving error, but as PR for  `sqs-workflow-improvements` was still a draft, i thought that you was aware of this and was still working on them. So i do not "touched" them.

**Comment by cristim** [comment]
Sounds good, thanks!

I'll take care of the rest next week.

**Pull request merged**
