### PR TITLE
Feat/event based instance replacement - Merged all "new" commit from master

### PR DESCRIPTION
**Pull request by mello7tre**
# Issue Type

- Feature Pull Request

## Summary

Merged one by one the "new" commit to align branch to master.
from:
647337e "Updating AWS SDK to latest version"
to the latest one:
c9c3ff1 "Use the larger of min-OD-instances and (min-OD-percent * current)"

## Code contribution checklist

1. [X] I hereby allow the Copyright holder the rights to distribute this piece of
   code under any software license.
1. [ ] The contribution fixes a single existing github issue, and it is linked
   to it.
1. [ ] The code is as simple as possible, readable and follows the idiomatic Go
  [guidelines](https://golang.org/doc/effective_go.html).
1. [ ] All new functionality is covered by automated test cases so the overall
  test coverage doesn't decrease.
1. [X] No issues are reported when running `make full-test`.
1. [ ] Functionality not applicable to all users should be configurable.
1. [ ] Configurations should be exposed through Lambda function environment
   variables which are also passed as parameters to the
   [CloudFormation](https://github.com/cristim/autospotting/blob/master/cloudformation/stacks/AutoSpotting/template.yaml)
   and
   [Terraform](https://github.com/autospotting/terraform-aws-autospotting/main.tf)
   stacks defined as infrastructure code.
1. [ ] Global configurations set from the infrastructure stack level should also
   support per-group overrides using tags.
1. [ ] Tags names and expected values should be similar to the other existing
   configurations.
1. [ ] Both global and tag-based configuration mechanisms should be tested and
  proven to work using log output from various test runs.
1. [ ] The logs should be kept as clean as possible (use log levels as
  appropriate) and formatted consistently to the existing log output.
1. [ ] The documentation is updated to cover the new behavior, as well as the
   new configuration options for both stack parameters and tag overrides.
1. [ ] A code reviewer reproduced the problem and can confirm the code
  contribution actually resolves it.

### CODE REVIEW

**Comment by cristim** [comment]
Oh, I  didn't notice the conflicts, please also have a look at those.

**Comment by mello7tre** [comment]
Resolved them, they were mostly code formatting differences

**Comment by cristim** [comment]
Thanks again!

**Comment by mello7tre** [comment]
I am looking forward to a merge with master.

By the way, as already told you, i have an autospotting version builded on feat branch (commit 565b6448132f9d48f4c02f0ad7fcd3da42066a26) on my dev infra running from months without any problems.

Last week i deployed it on production too (on an ecs-cluster that autoscale based on load) and found a problem.
I fixed it in my last push on this PR:
https://github.com/AutoSpotting/AutoSpotting/pull/433/commits/af6ccfcb657302f0ae048edbe942b1c1fdb6a679

there you can find the description of the problem too.

In the next week i will test in dev a version builded on event branch with this PR merge.

**Comment by cristim** [comment]
Thanks, good catch!

**Pull request merged**
